name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo using the latest action version
      - uses: actions/checkout@v3  # Updated to the latest version

      # Generates the snake  
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Show the status of the build for debugging purposes
      - run: git status

      # Push the changes using an updated action
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Use the latest or a compatible version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Update to use a compatible version of GitHub Pages action
      - uses: crazy-max/ghaction-github-pages@v2.5.0  # Example version, check for the latest version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
